services:
  - type: web
    name: pneumonet
    env: python
    plan: free
    buildCommand: pip install -r requirements_deploy.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.0"
